language: rust
rust:
- stable
- beta
- nightly
cache: cargo
script:
- cargo test --all
matrix:
  include:
  - rust: nightly-2018-01-28
    env: CLIPPY=YESPLEASE
    script: |
        cargo install clippy --vers "0.0.183"
        (cd waltz && cargo clippy) &&
        (cd waltz_cli && cargo clippy)
notifications:
  email:
    on_success: never
branches:
  except:
  - staging.tmp
