language: rust
rust:
- stable
- beta
- nightly
cache: cargo
script:
- cargo test --all
matrix:
  include:
  - rust: 1.29.1
    env: CLIPPY=YESPLEASE
    before_script: rustup component add clippy-preview
    script: cargo clippy --all -- -D warnings
  - rust: 1.29.1
    env: RUSTFMT=YESPLEASE
    before_script: rustup component add rustfmt-preview
    script: cargo fmt --all -- --check
notifications:
  email:
    on_success: never
branches:
  except:
  - staging.tmp
