[package]
authors = ["Pascal Hertleif <killercup@gmail.com>"]
name = "waltz"
version = "0.2.0"

[dependencies]
log = "0.3.6"
pulldown-cmark = "0.0.8"
regex = "0.2.0"
lazy_static = "0.2.4"
error-chain = "0.10.0"
slog = "1.4.0"
slog-envlogger = "0.5.0"
slog-stdlog = "1.1.0"
slog-term = "1.3.4"
