[package]
name = "waltz_cli"
version = "0.1.0"
authors = ["Pascal Hertleif <killercup@gmail.com>"]
readme = "../Readme.md"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "Cargo.toml"]
repository = "https://github.com/killercup/waltz"
keywords = ["markdown", "documentation", "testing"]
categories = ["development-tools::testing"]

[dependencies]
waltz = { path = "../waltz" }
pulldown-cmark = "0.0.8"
slog = "1.4.0"
slog-envlogger = "0.5.0"
slog-stdlog = "1.1.0"
slog-term = "1.3.4"
