[package]
authors = ["Pascal Hertleif <killercup@gmail.com>"]
name = "waltz"
version = "0.2.0"
readme = "../Readme.md"
repository = "https://github.com/killercup/waltz"

[dependencies]
log = "0.3.6"
pulldown-cmark = "0.0.8"
regex = "0.2.0"
lazy_static = "0.2.4"
error-chain = "0.10.0"

[dev-dependencies]
tempdir = "0.3"
unindent = "0.1"
