# .github/workflows/lint.yml
name: lint
on:
  workflow_dispatch:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      # with:
      #   repository: 'asears/actions'
      # - uses: asears/actions/lint-rust@v1
      #   with:
      #     project-directory: .
      - name: Lint with cargo fmt
        run: cargo fmt -- --check
      - name: Lint with cargo clippy
        run: cargo clippy -- -D warnings
      - name: cargo verify-project
        run: cargo verify-project

