# .github/workflows/lint.yml
name: lint
on:
  workflow_dispatch:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'asears/actions'
      - uses: asears/actions/lint-rust@v1
        with:
          project-directory: .
