# .github/workflows/lint.yml
name: lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: asears/actions/lint-rust@v1
        with:
          project-directory: .
