# .github/workflows/security.yml
name: securityscan
on:
  push:
  workflow_dispatch:

jobs:
  scan-security:
    uses: asears/actions/.github/workflows/scan-security/action.yml@v1
    with:
      project-directory: ./
  scan-secrets:
    uses: asears/actions/.github/workflows/scan-secrets/action.yml@v1
    with:
      project-directory: ./

