# .github/workflows/security.yml
name: securityscan
on: push

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: asears/actions/scan-secrets@v1
        with:
          project-directory: ./
